### ISSUE TITLE
Module disappeared from registry

### ISSUE THREAD

**Issue by ghost** [Azure/terraform-azurerm-avm-res-storage-storageaccount#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

v1.6.6

### Module Version

~> 0.1

### AzureRM Provider Version

~> 3.72

### Affected Resource(s)/Data Source(s)

all

### Terraform Configuration Files

```hcl
Not applicable
```

### tfvars variables values

```hcl
Not applicable
```

### Debug Output/Panic Output

```shell
│ Error: Module not found
│
│   on storage.tf line 19:
│   19: module "st" {
│
│ Module "st" (from storage.tf:19) cannot be found in the module registry at registry.terraform.io.
```

### Actual Behaviour

Module disappeared from Hachicorp Registry

https://registry.terraform.io/modules/Azure/storage-account/azure/latest

![image](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/assets/144891384/9e70f376-5740-438d-a0a2-9b6d37814247)

### Steps to Reproduce

terraform init

**Comment by matt-FFFFFF** [comment]
The module repo has been renamed and we are going to make breaking changes to align with AVM. Any previous tage have been removed and will will publish to the registry with the new name in due course.

Continuation under the old name would have led to confusion due to github's URL redirection, so we have taken the decision to remove all release tags for now.
